export const colors = {
	COLOR_PRIMARY: "#f96163",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};

export const recipeList = [
	{
		id: "1",
		name: "Tuna Tartare",
		image: require("../assets/images/tuna.png"),
		rating: "4.2",
		ingredients: ["Tuna Segar", "Jeruk Nipis", "Bawang Merah", "Alpukat"],
		time: "40 mins",
		difficulty: "Medium",
		portion: "2 person",
		color: "#006A4E",
		description:
			"Hidangan lezat dan menyegarkan yang menyajikan tuna segar dicampur dengan jeruk nipis dan renyahnya bawang merah dan alpukat.",
		steps: [
			"Potong dadu tuna segar",
			"Cincang halus bawang merah dan alpukat.",
			"Campur tuna, bawang merah, dan alpukat dalam mangkuk.",
			"Peras jeruk nipis ke atas campuran dan aduk perlahan.",
			"Sajikan dan Selamat Menikmati",
		],
	},
	{
		id: "2",
		name: "Lasagna",
		image: require("../assets/images/lasgana.png"),
		rating: "3.6",
		ingredients: [
			"Mie Lasagna",
			"Daging Giling",
			"Keju Ricotta",
			"Saus Tomat",
		],
		time: "40 mins",
		difficulty: "Medium",
		portion: "2-4 Person",
		color: "#f39c12",
		description:
			"Makanan klasik Italia yang menenangkan dengan lapisan mie lasagna, daging giling beraroma, keju ricotta yang kaya rasa, dan saus tomat yang tajam.",
		steps: [
			"Masak mie lasagna sesuai petunjuk kemasan.",
			"Tumis daging giling dalam wajan dan bumbui dengan bumbu.",
			"Lapisi mie lasagna, daging sapi, keju ricotta, dan saus tomat ke dalam loyang.",
			"Ulangi lapisan tersebut dan panggang dalam oven sampai bergelembung dan berwarna keemasan.",
			"Biarkan agak dingin sebelum disajikan.",
		],
	},
	{
		id: "3",
		name: "Hot Dog",
		image: require("../assets/images/hotdog.png"),
		rating: "4.6",
		ingredients: ["Roti Hot Dog", "Sosis", "Saus", "Mustard"],
		time: "40 mins",
		difficulty: "Medium",
		portion: "1 Person",
		color: "#FF0000",
		description:
			"Masakan Amerika klasik, roti hot dog yang diisi dengan sosis, ditaburi saus tomat dan mustard untuk keseimbangan rasa yang sempurna.",
		steps: [
			"Panggang atau panaskan sosis hingga matang.",
			"Masukkan sosis ke dalam roti hot dog.",
			"Peras saus tomat dan mustard di atas sosis.",
			"Sajikan dengan makanan pendamping favorit Anda dan nikmatilah!",
		],
	},
	{
		id: "4",
		name: "Manchuria",
		image: require("../assets/images/manchurian.png"),
		rating: "3.6",
		ingredients: ["Sayur Kol", "Kecap", "Jahe", "Bawang Putih"],
		time: "30 mins",
		difficulty: "Easy",
		portion: "3 Person",
		color: "#d35400",
		description:
			"Hidangan Indo-Cina populer dengan potongan sayur kol renyah yang ditaburi saus beraroma yang dibuat dengan kecap, jahe, dan bawang putih.",
		steps: [
			"Potong sayur kol menjadi kuntum dan rebus.",
			"Siapkan saus dengan mencampurkan kecap, jahe, dan bawang putih.",
			"Goreng atau goreng sayur kol hingga renyah.",
			"Masukkan sayut kol goreng ke dalam saus hingga terlapisi rata.",
			"Hiasi dengan daun bawang cincang dan sajikan panas.",
		],
	},
	{
		id: "5",
		name: "Ayam Panggang",
		image: require("../assets/images/chicken.png"),
		rating: "2.2",
		ingredients: ["Dada Ayam", "Garam", "Lada Hitam", "Minyak Zaitun"],
		time: "45 mins",
		difficulty: "Medium",
		portion: "4 Person",
		color: "#8d4004",
		description:
			"Hidangan ayam lezat yang dibumbui dengan campuran garam dan lada hitam, lalu dimasak hingga sempurna dengan sedikit minyak zaitun.",
		steps: [
			"Panaskan oven sampai suhu yang ditentukan.",
			"Bumbui dada ayam dengan garam dan lada hitam.",
			"Panaskan minyak zaitun dalam wajan dengan api sedang-besar.",
			"Tumis dada ayam di kedua sisi hingga berwarna cokelat keemasan.",
			"Pindahkan ayam ke dalam oven dan panggang sampai matang.",
			"Sajikan panas dan nikmati ayam beraroma Anda!",
		],
	},
	{
		id: "6",
		name: "Cupcakes",
		image: require("../assets/images/cupcakes.png"),
		rating: "5.0",
		ingredients: ["Tepung", "Gula", "Telur", "Mentega"],
		time: "60 mins",
		difficulty: "Medium",
		portion: "20 Person",
		description:
			"Cupcakes lezat yang dibuat dengan perpaduan sempurna antara tepung, gula, telur, dan mentega, cocok untuk segala acara.",
		steps: [
			"Panaskan lebih dulu oven hingga suhu yang ditentukan.",
			"Siapkan adonan cupcake dengan mencampurkan semua bahan menjadi satu.",
			"Lapis loyang muffin dengan cupcake liner.",
			"Isi setiap loyang dengan adonan dan panggang dalam oven.",
			"Biarkan cupcakes dingin, lalu bekukan dan hias sesuai keinginan.",
			"Manjakan diri dengan camilan manis ini dan nikmati rasanya!",
		],
	},
	{
		id: "7",
		name: "Kari",
		image: require("../assets/images/curry.png"),
		rating: "4.8",
		ingredients: ["Daging", "Bubuk Kari", "Santan", "Rempah-rempah"],
		time: "55 mins",
		difficulty: "Hard",
		portion: "4 Person",
		color: "#d35400",

		description:
			"Hidangan kari yang kaya dan beraroma dengan potongan daging empuk yang dimasak dengan campuran bubuk kari, santan, dan rempah-rempah yang beraroma.",
		steps: [
			"Marisinkan daging dengan bumbu dan diamkan sebentar.",
			"Panaskan minyak dalam panci besar lalu tumis daging yang sudah direndam hingga kecoklatan.",
			"Tambahkan bubuk kari dan aduk untuk melapisi daging.",
			"Tuang santan dan didihkan.",
			"Tutup dan biarkan kari mendidih hingga daging empuk dan bumbunya menyatu.",
			"Sajikan kari dengan nasi atau roti dan nikmati kelezatannya!",

		],
	},
	{
		id: "8",
		name: "Ramen",
		image: require("../assets/images/ramen-org.png"),
		rating: "4.2",
		ingredients: ["Mie Ramen", "Kecap", "Telur", "Sayuran"],
		time: "35 mins",
		difficulty: "Easy",
		portion: "4 Person",
		color: "#f96163",
		description:
			"Semangkuk ramen yang menenangkan dengan mie yang nikmat, kuah kaldu berbahan dasar kecap yang gurih, sayuran yang empuk, dan telur yang direbus sempurna.",
		steps: [
			"Rebus mie ramen sesuai petunjuk kemasan.",
			"Di dalam panci, didihkan air dan tambahkan kecap asin untuk kuahnya.",
			"Tambahkan sayuran cincang dan biarkan masak sampai empuk.",
			"Rebus telur hingga tingkat kematangan yang diinginkan, lalu kupas dan iris.",
			"Rakit mangkuk ramen dengan meletakkan mie matang, sayuran, dan irisan telur.",
			"Sendokkan kaldu panas ke atas bahan-bahannya dan bersiaplah untuk menikmati ramen buatanmu!",
		],
	},
];
